
import { Geist, Geist_Mono } from "next/font/google";
import '@stream-io/video-react-sdk/dist/css/styles.css';


import "./globals.css";
import { PreJoinProvider } from "@/context/PreJoinContext"; // <-- import here
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <PreJoinProvider>
          <Toaster position="top-right" />
          {children}
        </PreJoinProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
